### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by NikkieDev** [stuncs69/papaya.js#3]
Papaya connects to a centralized websocket, which will display "Servers currently running Papaya instances: "
& Every time a new papaya.js project is created using npm create papaya@latest, add 1 to the amount of Papaya projects existing, displayed on the default page as "Existing papaya projects". The default page being the page that papaya creates upon initializing the project

**Comment by stuncs69** [comment]
Will not fix. Papaja.js instances are designed to be run independently from each other, and creating this statistic would break this design choice.
